name: hackcraft
description: A Dart library for Minecraft hacking and automation.
version: 0.0.1
repository: https://github.com/yourusername/hackcraft-dart
homepage: https://github.com/yourusername/hackcraft-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Add your package dependencies here
  web_socket_channel: ^3.0.3
  async: ^2.13.0
  logging: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  coverage: ^1.6.0

# Add any additional configuration here 